source 'https://github.com/CocoaPods/Specs.git'

target 'AsyncOpKit', :exclusive => true do
    use_frameworks!
    pod "AsyncOpKit", :path => "../"
end

target 'Tests', :exclusive => true do
    use_frameworks!
    pod "AsyncOpKit", :path => "../"

    pod 'Quick'
    pod 'Nimble'
end
